# render.yaml
services:
  - type: web
    name: hris-backend
    runtime: node
    repo: https://github.com/Yesagain-site/HRIS
    branch: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://yespeople.netlify.app
      - key: PORT
        value: 5000
